### ISSUE TITLE
BigQuery connection RuntimeError

### ISSUE THREAD

**Issue by djfrancesco** [sfu-db/connector-x#304]
Dear ConnectorX team, I have an issue concerning a Big Query connection. I am just starting with Big Query so maybe I am doing something wrong. Here is a Python script, where I connect to a data base using: 
1 - Google BigQuery API client library : OK
2 - SQLAlchemy Dialect for BigQuery : OK
3 - ConnectorX : NOK
They all use the same JSON authentification file path and the same test query.

```python
import os

import connectorx as cx
from google.cloud import bigquery
from sqlalchemy.engine import create_engine

BQ_AUTHENTICATION_FILE_PATH = (
    "/home/francois/keys/GCP/my_key.json"
)
SQL_QUERY = "SELECT COUNT(*) FROM faker.faker1000"
NROWS = 1000

# Google BigQuery API client library
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = BQ_AUTHENTICATION_FILE_PATH
client = bigquery.Client()
query_job = client.query(SQL_QUERY)
results = query_job.result()
count = next(results)[0]
assert count == NROWS

# SQLAlchemy Dialect for BigQuery
engine = create_engine("bigquery://", credentials_path=BQ_AUTHENTICATION_FILE_PATH)
with engine.connect() as connection:
    result = connection.execute(SQL_QUERY).fetchone()
count = result[0]
assert count == NROWS

# ConnectorX
connect_string = "bigquery://" + BQ_AUTHENTICATION_FILE_PATH
df = cx.read_sql(connect_string, SQL_QUERY)
```

I get this error with ConnectorX:

        RuntimeError: Response error (error: ResponseError { error: NestedResponseError { code: 404, errors: [{"reason": "notFound", "message": "Not found: Job aetp:job_85iWj4QbTtcAMVzj5s7xsSZkEC8F", "domain": "global"}], message: "Not found: Job aetp:job_85iWj4QbTtcAMVzj5s7xsSZkEC8F", status: "NOT_FOUND" } })

Maybe I need to specify my location (europe-west3)? The package versions are the following ones:

        connectorx version : 0.3.0
        sqlalchemy version : 1.4.27
        sqlalchemy-bigquery version : 1.4.4
        google.cloud.bigquery version : 3.2.0

François

**Comment by Wukkkinz-0725** [comment]
Hi @djfrancesco , thanks for giving the concrete example. 

I tested your example on my database and **all three libraries(GCP, SQLAlchemy and connectors)  are working**. Besides, I think your package version is right and the location does not matter.

Can you specify more about your configuration and your data type? I want to make sure what cause the `Not Found job` error.

**Comment by djfrancesco** [comment]
Thanks for your answer @Wukkkinz-0725. Do you think of anything specific regarding my configuration and data type? I am running Linux / Python 3.9 in a conda environment.

I tried to query different tables from our BQ datasets and always get the same behavior (GCP OK, SQLAlchemy OK, ConnectorX NOK `Job Not found`). I also tried querying a public dataset:
```
SQL_QUERY = """SELECT COUNT(*) FROM 
 (SELECT date, channelGrouping as channel, totals.visits, totals.transactions, totals.transactionRevenue 
FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20170801` LIMIT 1000)"""
```
and the 3 libraries are working well.

**Comment by phanindraramesh-a10** [comment]
I have the same issue. I see that the job id in error message does not contain the location. Where as, If I run the query on Bigquery query console,the job id contains location. Is there a way to pass the location of the data sets in run_sql?

**Comment by wangxiaoying** [comment]
Hi @djfrancesco , we have merged the PR @phanindraramesh-a10  submitted and released an alpha version. Can you try `pip install connectorx==0.3.1a6` to see whether it fixes the issue?

**Comment by djfrancesco** [comment]
Hi, I checked and it worked with the 0.3.1a6 version (I also checked that I still get the RuntimeError with the 0.3.0 version) ! Thank you @phanindraramesh-a10 and @wangxiaoying
